### PR TITLE
Add password complexity check.

### PR DESCRIPTION
**Pull request by alissarjohnson**
Current error message doesn't seem to be overwritten by message in devise.en.yml --> working on that

### CODE REVIEW

**Comment by zfigura** [comment]
What are the actual password requirements? Our error message should actually communicate those, rather than vaguely saying "make it stronger".

**Comment by Mizkoeu** [comment]
The password strength functionality is working. But will need to fix error message in the future. Opening an issue on Github. [https://github.com/CSC322-Grinnell/volunteer-board/issues/138](url)

**Comment by zfigura** [comment]
Okay, we also should change our message to be something more descriptive.

**Comment by zfigura** [comment]
And if the library doesn't make it possible to have clearly defined requirements, then I'd strongly advocate for not using it.

**Pull request merged**
